apiVersion: polling.gitops.tools/v1alpha1
kind: PolledRepository
metadata:
  labels:
    app.kubernetes.io/name: gitpoller-controller
    app.kubernetes.io/managed-by: kustomize
  name: polledrepository-sample
spec:
  # TODO(user): Add fields here
